(ns qualityclj.routes.home
  (:require [qualityclj.views.layout :as layout]
            [clojure.java.io :as io]
            [compojure.core :refer :all]))

(defn home []
  (layout/common
   [:div#jumbo]
   [:div.container-fluid
    [:h2 "Sample"]]))

(defn about []
  (layout/common
   [:div#header.container-fluid
    [:h2 "About"]
    [:p "Quality Clojure will take a Clojure git repository, import it
    into Codeq, and run a series of linters against it. The linters
    include kibit, eastwood, and bikeshed. There's also the capability
    to add user comments to different parts of the file, or to other
    notes generated by a linter. Users can flag a note or comment for
    various reasons as well."]
    [:p "Quality Clojure was envisioned as a contender for the 2014
   Clojure Cup, but sadly was not finished in time to show off! The
   team plans on completing the work that they've started, but in the
   meantime, the main page shows an example of what Quality Clojure
   might eventually look like."]
    [:p "This site is (mostly) static, aside from the front-end
    Clojurescript adding information about the file displayed on the
    main page, and putting the note bubbles in the approximately
    correct location."]]  ))

(defroutes home-routes
  (GET "/" [] (home))
  (GET "/about" [] (about)))
